// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright 2025-2026 alwaysEpic

//! Single source of truth for the BlueRetro QEMU harness fixtures.
//!
//! The Python harness in `tests/blueretro/` cannot read the Rust descriptor
//! constants directly, so this test emits them (plus the wire bytes our
//! serializers produce for each button) into `tests/blueretro/fixtures.json`.
//!
//! Default mode: regenerate the JSON in memory and assert it byte-matches the
//! committed file. This runs as part of `scripts/ci.sh`, so any edit to the
//! descriptors or serializers that isn't reflected in the harness fixtures
//! fails CI.
//!
//! Regenerate after an intentional change:
//! ```sh
//! (cd maple-protocol && UPDATE_FIXTURES=1 cargo test --test blueretro_fixtures)
//! ```

// "BlueRetro" is a product name, not code.
#![allow(clippy::doc_markdown)]

use std::fmt::Write as _;

use maple_protocol::xbox_hid::{
    buttons, GamepadReport, HID_REPORT_DESCRIPTOR_EXT, HID_REPORT_DESCRIPTOR_STD,
};

const FIXTURE_PATH: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../tests/blueretro/fixtures.json"
);

/// Physical buttons in a stable order, paired with their logical bitmask.
const BUTTONS: &[(&str, u16)] = &[
    ("a", buttons::A),
    ("b", buttons::B),
    ("x", buttons::X),
    ("y", buttons::Y),
    ("lb", buttons::LB),
    ("rb", buttons::RB),
    ("back", buttons::BACK),
    ("start", buttons::START),
    ("l3", buttons::L3),
    ("r3", buttons::R3),
];

fn hex(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        let _ = write!(s, "{b:02x}");
    }
    s
}

/// `std` = legacy gappy wire layout (`to_bytes_ms`), `ext` = contiguous (`to_bytes`).
fn report_pair(buttons: u16) -> (String, String) {
    let r = GamepadReport {
        buttons,
        ..Default::default()
    };
    (hex(&r.to_bytes_ms()), hex(&r.to_bytes()))
}

fn build_fixtures_json() -> String {
    let mut out = String::new();
    out.push_str("{\n");
    out.push_str("  \"_comment\": \"Generated by `UPDATE_FIXTURES=1 cargo test -p maple-protocol --test blueretro_fixtures`. Do not edit by hand.\",\n");
    out.push_str("  \"descriptors\": {\n");
    let _ = writeln!(out, "    \"std\": \"{}\",", hex(HID_REPORT_DESCRIPTOR_STD));
    let _ = writeln!(out, "    \"ext\": \"{}\"", hex(HID_REPORT_DESCRIPTOR_EXT));
    out.push_str("  },\n");

    let (n_std, n_ext) = report_pair(0);
    let _ = writeln!(
        out,
        "  \"neutral\": {{ \"std\": \"{n_std}\", \"ext\": \"{n_ext}\" }},"
    );

    out.push_str("  \"buttons\": {\n");
    for (i, (name, mask)) in BUTTONS.iter().enumerate() {
        let (std, ext) = report_pair(*mask);
        let comma = if i + 1 < BUTTONS.len() { "," } else { "" };
        let _ = writeln!(
            out,
            "    \"{name}\": {{ \"std\": \"{std}\", \"ext\": \"{ext}\" }}{comma}"
        );
    }
    out.push_str("  }\n}\n");
    out
}

#[test]
fn blueretro_fixtures_up_to_date() {
    let generated = build_fixtures_json();

    if std::env::var_os("UPDATE_FIXTURES").is_some() {
        let path = std::path::Path::new(FIXTURE_PATH);
        if let Some(dir) = path.parent() {
            std::fs::create_dir_all(dir).expect("create fixtures dir");
        }
        std::fs::write(path, &generated).expect("write fixtures.json");
        eprintln!("wrote {FIXTURE_PATH}");
        return;
    }

    let committed = std::fs::read_to_string(FIXTURE_PATH).unwrap_or_else(|e| {
        panic!(
            "could not read {FIXTURE_PATH}: {e}\n\
             generate it with `(cd maple-protocol && UPDATE_FIXTURES=1 cargo test --test blueretro_fixtures)`"
        )
    });

    assert_eq!(
        committed, generated,
        "tests/blueretro/fixtures.json is stale — the HID descriptors or report \
         serializers changed. Regenerate with \
         `(cd maple-protocol && UPDATE_FIXTURES=1 cargo test --test blueretro_fixtures)`"
    );
}
