// Build script: generates pixel-art glyphs for the VMU profile splash by
// rasterizing parametric paths. Output is included by src/vmu.rs.
//
// We compute these at build time rather than encoding bytes by hand because
// hand-encoding a smooth Archimedean spiral at 32×24 doesn't converge — every
// attempt looks like concentric rings rather than a continuous ribbon.

use std::env;
use std::f64::consts::PI;
use std::fs;
use std::path::Path;

const WIDTH: usize = 32;
const HEIGHT: usize = 24;
const BYTES: usize = WIDTH * HEIGHT / 8;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = env::var("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir).join("glyph_dreamcast.rs");

    let bytes = generate_swirl();

    let mut content = String::new();
    content.push_str("// Generated by build.rs — do not edit.\n");
    content.push_str("/// Dreamcast swirl glyph (Generic profile), rasterized from a parametric\n");
    content.push_str("/// Archimedean spiral. 1.75 turns ending at upper-right, mirrored\n");
    content.push_str("/// vertically so the outer terminus lands at the lower-right.\n");
    content.push_str("#[rustfmt::skip]\n");
    content.push_str(&format!("pub const GLYPH_DREAMCAST: [u8; {BYTES}] = [\n"));
    for row in 0..HEIGHT {
        content.push_str("    ");
        for col_byte in 0..(WIDTH / 8) {
            let b = bytes[row * (WIDTH / 8) + col_byte];
            content.push_str(&format!("0x{b:02X}, "));
        }
        // Visualise as a comment for inspectability in the generated file.
        content.push_str("// ");
        for col in 0..WIDTH {
            let b = bytes[row * (WIDTH / 8) + col / 8];
            let bit = (b >> (7 - (col % 8))) & 1;
            content.push(if bit == 1 { 'X' } else { '.' });
        }
        content.push('\n');
    }
    content.push_str("];\n");

    fs::write(&out_path, content).unwrap();
}

/// Plot a 3-pixel-wide ribbon along an Archimedean spiral, plus a tail that
/// extends from the spiral's outer terminus outward to the upper-right.
fn generate_swirl() -> [u8; BYTES] {
    let mut frame = [0u8; BYTES];

    // Spiral parameters (canvas coordinates: x=col, y=row, origin at top-left).
    // `phase` rotates the spiral's outer terminus (t=0). With phase = 7π/4 the
    // ribbon's outer end lands at the upper-right of the canvas, matching the
    // reference logo where the tail extends up-and-right from that corner.
    let cx = 15.5_f64;
    let cy = 11.5_f64;
    let r_outer = 11.0_f64;
    let r_inner = 1.0_f64;
    let turns = 1.75_f64;
    let stroke = 1.4_f64;
    let phase = 7.0 * PI / 4.0;

    for y in 0..HEIGHT {
        for x in 0..WIDTH {
            let dx = x as f64 - cx;
            let dy = y as f64 - cy;
            let r = (dx * dx + dy * dy).sqrt();
            // atan2 returns (-π, π]; normalise to [0, 2π).
            let theta = {
                let t = dy.atan2(dx);
                if t < 0.0 {
                    t + 2.0 * PI
                } else {
                    t
                }
            };

            let mut on = false;

            // The spiral passes through angle θ at multiple radii (one per turn).
            // We shift θ by `phase` so the spiral's outer terminus (t=0) lands
            // at the chosen orientation rather than the default right side.
            // For each turn k, the parametric arc length t_k = (θ - phase) + 2π·k,
            // and the radius at that point is r_outer - (r_outer-r_inner)·t_k/max_t.
            let max_t = 2.0 * PI * turns;
            let theta_shifted = {
                let s = theta - phase;
                let twopi = 2.0 * PI;
                ((s % twopi) + twopi) % twopi
            };
            for k in 0..=(turns.ceil() as i32 + 1) {
                let t_k = theta_shifted + 2.0 * PI * k as f64;
                if t_k < 0.0 || t_k > max_t {
                    continue;
                }
                let r_k = r_outer - (r_outer - r_inner) * t_k / max_t;
                if (r - r_k).abs() < stroke {
                    on = true;
                    break;
                }
            }

            // (Tail extension intentionally omitted — straight extrapolation
            // from the spiral's outer terminus angles differently than the
            // ribbon's curve, producing a visible kink. Better to just end.)

            if on {
                let byte_idx = y * (WIDTH / 8) + x / 8;
                let bit_idx = 7 - (x % 8);
                frame[byte_idx] |= 1 << bit_idx;
            }
        }
    }

    // Vertical mirror (flip top↔bottom): row i swaps with row (HEIGHT-1-i).
    let row_bytes = WIDTH / 8;
    let mut mirrored = [0u8; BYTES];
    for row in 0..HEIGHT {
        let src = row * row_bytes;
        let dst = (HEIGHT - 1 - row) * row_bytes;
        mirrored[dst..dst + row_bytes].copy_from_slice(&frame[src..src + row_bytes]);
    }

    mirrored
}
