''' Regression tests: does a BlueRetro adapter map our profiles correctly?

These reproduce / guard issue #2
(https://github.com/alwaysEpic/pulsar-dreamcast-ble/issues/2) in software, with
no nRF hardware. They run against BlueRetro's own firmware under QEMU
(qemu-system-xtensa), driven over the injector websocket:

  send_name      -> advertise the name a given profile uses
  send_hid_desc  -> hand BlueRetro the exact HID report descriptor we serve
  send_to_bridge -> feed report bytes (ours, or generated by BlueRetro's helpers)

Every assertion is at the `generic_input` stage — where BlueRetro decides, from
the descriptor, which physical input maps to which normalized function. That is
exactly the stage issue #2 is about, and it is system-independent, so `system.DC`
here is just the connection target.

A red STD test is the harness doing its job: it means our STD descriptor does not
parse the way a genuine Xbox One S BLE controller does, i.e. issue #2 reproduced.
Once the descriptor is fixed these go (and stay) green.

Fixtures (descriptor + report bytes) come from the Rust source via
`maple-protocol/tests/blueretro_fixtures.rs` (kept in sync by scripts/ci.sh).
This file is copied into BlueRetro's tests/ dir at CI time so the imports below
resolve against their conftest / injector / device_data.
'''
import json
import os
from itertools import islice

import pytest

from bit_helper import bit, swap16
from device_data.br import system, dev_mode, bt_conn_type, axis, hat_to_ld_btns
from device_data.xbox import xbox_ble_btns_mask, xbox_axes
from device_data.gc import gc_axes
from device_data.test_data_generator import axes_test_data_generator


# Names match PROFILE_STD / PROFILE_EXT gap_name in src/ble/profile.rs.
DEVICE_NAME_STD = 'Xbox Wireless Controller'
DEVICE_NAME_EXT = 'Dreamcast Wireless Controller'

with open(os.path.join(os.path.dirname(__file__), 'fixtures.json'), encoding='utf-8') as _f:
    FIXTURES = json.load(_f)


def _wire_btns(report_hex):
    ''' Extract the 24-bit button field (bytes 13-15) from a 16-byte report. '''
    b = bytes.fromhex(report_hex)
    return b[13] | (b[14] << 8) | (b[15] << 16)


def _expected_generic(wire):
    ''' Mirror BlueRetro's own bit->generic mapping for the Xbox BLE controller,
        so this stays in lockstep with upstream device_data/xbox.py. '''
    generic = 0
    for gen_bit, src_mask in enumerate(xbox_ble_btns_mask):
        if src_mask and (wire & src_mask):
            generic |= bit(gen_bit)
    return generic


def _check_buttons(blueretro, descriptor):
    ''' Send `descriptor`, then our STD (gappy) report bytes for each button, and
        return a list of mapping failures. Shared by the control and the STD test
        so the *only* difference between them is the descriptor under test. '''
    blueretro.send_name(DEVICE_NAME_STD)
    blueretro.send_hid_desc(descriptor)

    for _ in range(2):
        blueretro.send_to_bridge(0x01, FIXTURES['neutral']['std'])

    failures = []
    for name, reports in FIXTURES['buttons'].items():
        report = reports['std']
        rsp = blueretro.send_to_bridge(0x01, report)

        wire = _wire_btns(report)
        expected = _expected_generic(wire)
        got = rsp['generic_input']['btns'][0]

        if rsp['wireless_input']['btns'] & 0xFFFFFF != wire:
            failures.append(
                f"{name}: descriptor parse mismatch — "
                f"sent wire=0x{wire:06x}, BlueRetro read=0x{rsp['wireless_input']['btns'] & 0xFFFFFF:06x}")
        if got != expected:
            failures.append(
                f"{name}: wire=0x{wire:06x} expected generic=0x{expected:08x} got=0x{got:08x}")
    return failures


@pytest.mark.parametrize('blueretro', [[system.DC, dev_mode.PAD, bt_conn_type.BT_LE]], indirect=True)
def test_harness_control_reference_xbox(blueretro):
    ''' Control / baseline. Runs the exact assertion path below against
        BlueRetro's OWN reference Xbox One S BLE descriptor (imported from their
        suite). This MUST be green: it proves the harness is wired correctly and
        our assertions are sound, so a red STD test is a real finding about our
        descriptor — not a harness bug. If this is red, fix the harness first. '''
    # Hard import (not importorskip): this control is the harness gate, so a
    # missing/renamed reference module must FAIL the job, not silently skip it.
    try:
        import pytest_xbox_ble_controller as xbox_ref
    except ImportError as exc:
        pytest.fail(
            "CONTROL BROKEN — BlueRetro reference module 'pytest_xbox_ble_controller' "
            f"could not be imported ({exc}); the harness gate is gone, fix it before "
            "trusting any STD result.")
    failures = _check_buttons(blueretro, xbox_ref.HID_DESC)
    assert not failures, (
        "CONTROL FAILED — harness wiring/assertions are wrong, not our descriptor:\n  "
        + "\n  ".join(failures))


@pytest.mark.parametrize('blueretro', [[system.DC, dev_mode.PAD, bt_conn_type.BT_LE]], indirect=True)
def test_pulsar_std_buttons_mapping(blueretro):
    ''' Each physical button on the STD profile must decode to the right
        BlueRetro-generic button (the bug in issue #2). Only meaningful if the
        control above is green. '''
    failures = _check_buttons(blueretro, bytes.fromhex(FIXTURES['descriptors']['std']))
    assert not failures, "STD profile mis-maps buttons on BlueRetro:\n  " + "\n  ".join(failures)


@pytest.mark.parametrize('blueretro', [[system.DC, dev_mode.PAD, bt_conn_type.BT_LE]], indirect=True)
def test_pulsar_std_dpad_mapping(blueretro):
    ''' The hat switch (byte 12) must decode to the right D-pad directions.
        Mirrors BlueRetro's own Xbox BLE hat test against our STD descriptor. '''
    blueretro.send_name(DEVICE_NAME_STD)
    blueretro.send_hid_desc(bytes.fromhex(FIXTURES['descriptors']['std']))

    for _ in range(2):
        blueretro.send_to_bridge(0x01, FIXTURES['neutral']['std'])

    # hat nibble 0 = null/neutral, 1..8 = N, NE, E, ... ; 9..15 = out of range -> neutral.
    shifted_hat = hat_to_ld_btns[-1:] + hat_to_ld_btns[:-1]

    failures = []
    for hat_value, br_btns in enumerate(shifted_hat):
        rsp = blueretro.send_to_bridge(
            0x01,
            '00800080' '00800080' '00000000' f'0{hat_value:01x}' '000000')

        if rsp['wireless_input']['hat'] != hat_value:
            failures.append(
                f"hat {hat_value}: BlueRetro read hat={rsp['wireless_input']['hat']}")
        if rsp['generic_input']['btns'][0] != br_btns:
            failures.append(
                f"hat {hat_value}: expected d-pad=0x{br_btns:08x} got=0x{rsp['generic_input']['btns'][0]:08x}")

    assert not failures, "STD profile mis-maps the D-pad on BlueRetro:\n  " + "\n  ".join(failures)


@pytest.mark.parametrize('blueretro', [[system.DC, dev_mode.PAD, bt_conn_type.BT_LE]], indirect=True)
def test_pulsar_std_axes_scaling(blueretro):
    ''' Sticks (unsigned 0-65535, center 32768) and triggers (0-1023) must decode
        to the right axis with the right range/sign. Guards the signed-Logical-
        Maximum stick regression (the 0x26 FF FF -> -1 bug) and confirms our
        right-stick (Rx/Ry) and trigger (Z/Rz) usages land on the expected axes. '''
    blueretro.send_name(DEVICE_NAME_STD)
    blueretro.send_hid_desc(bytes.fromhex(FIXTURES['descriptors']['std']))

    for _ in range(2):
        blueretro.send_to_bridge(0x01, FIXTURES['neutral']['std'])

    failures = []
    for axes in axes_test_data_generator(xbox_axes, gc_axes, 0.0135):
        rsp = blueretro.send_to_bridge(
            0x01,
            f'{swap16(axes[axis.LX]["wireless"]):04x}{swap16(axes[axis.LY]["wireless"]):04x}'
            f'{swap16(axes[axis.RX]["wireless"]):04x}{swap16(axes[axis.RY]["wireless"]):04x}'
            f'{swap16(axes[axis.LM]["wireless"]):04x}{swap16(axes[axis.RM]["wireless"]):04x}'
            '00' '000000')

        for ax in islice(axis, 0, 6):
            if rsp['wireless_input']['axes'][ax] != axes[ax]['wireless']:
                failures.append(
                    f"{ax.name}: wireless expected {axes[ax]['wireless']} "
                    f"got {rsp['wireless_input']['axes'][ax]}")
            if rsp['generic_input']['axes'][ax] != axes[ax]['generic']:
                failures.append(
                    f"{ax.name}: generic expected {axes[ax]['generic']} "
                    f"got {rsp['generic_input']['axes'][ax]}")

    assert not failures, "STD profile mis-scales axes on BlueRetro:\n  " + "\n  ".join(failures)


@pytest.mark.xfail(reason="EXT targets Steam/PC (generic HID); its contiguous "
                          "Button 1-15 layout is expected to mis-map on BlueRetro, "
                          "whose generic-HID order is A,B,C,X,Y,Z. Probe only.",
                   strict=False)
@pytest.mark.parametrize('blueretro', [[system.DC, dev_mode.PAD, bt_conn_type.BT_LE]], indirect=True)
def test_pulsar_ext_buttons_probe(blueretro):
    ''' Characterize what BlueRetro does with the EXT profile. EXT is the
        xpadneo-style contiguous layout meant for Steam/Linux/Android, not for
        BlueRetro. This probe asserts the *correct* mapping (same generic button
        each physical button should produce) and is xfail-tolerant: XFAIL = EXT
        mis-maps on BlueRetro as expected; XPASS = it happens to work, revisit. '''
    blueretro.send_name(DEVICE_NAME_EXT)
    blueretro.send_hid_desc(bytes.fromhex(FIXTURES['descriptors']['ext']))

    for _ in range(2):
        blueretro.send_to_bridge(0x01, FIXTURES['neutral']['ext'])

    failures = []
    for name, reports in FIXTURES['buttons'].items():
        # The correct generic button is what the (known-good) STD wire produces.
        correct = _expected_generic(_wire_btns(reports['std']))
        rsp = blueretro.send_to_bridge(0x01, reports['ext'])
        got = rsp['generic_input']['btns'][0]
        if got != correct:
            failures.append(
                f"{name}: expected generic=0x{correct:08x} got=0x{got:08x}")

    assert not failures, "EXT profile mapping on BlueRetro:\n  " + "\n  ".join(failures)
