# SPDX-License-Identifier: GPL-3.0-or-later
"""Bake the Blender renders into the VMU frame table.

    uv run --with pillow --with numpy python bake_frames.py <renderdir> <out.rs> [preview.gif]

Each render is box-filtered to 48x32, then composed in 1-bit:
  - beams: 4x4 ordered (Bayer) dither, so their fade survives. Ordered, not error
    diffusion — error diffusion reshuffles every pixel each frame and the LCD shimmers.
  - star: a crisp disc; dithering its antialiased edge left it ragged.
  - sky: a few fixed background pixels.
  - flash: rays sized from the beam's angle to the line of sight (angles.json), so
    the burst grows and fades with the sweep instead of popping on one frame.
"""
import json
import sys
from pathlib import Path

import numpy as np
from PIL import Image

W, H = 48, 32
BAYER4 = (np.array([[0, 8, 2, 10], [12, 4, 14, 6], [3, 11, 1, 9], [15, 7, 13, 5]]) + 0.5) / 16
GAMMA = 0.8
YY, XX = np.mgrid[0:H, 0:W]
STAR = (XX - 23.5) ** 2 + (YY - 15.5) ** 2 <= 4.6**2
# Clear of the battery (x 36-47, y 0-6), which masks its whole box.
SKY = [(3, 4), (40, 10), (8, 26), (44, 22), (30, 29), (16, 8)]
FLASH_PEAK, FLASH_CONE = 10, 32  # ray length at 0 deg; zero at FLASH_CONE deg off the LOS


def load(path):
    im = np.asarray(Image.open(path).convert("L"), dtype=np.float32) / 255
    return im.reshape(H, im.shape[0] // H, W, im.shape[1] // W).mean(axis=(1, 3))


def compose(grey, angle):
    f = (grey**GAMMA > np.tile(BAYER4, (H // 4, W // 4))) & ~STAR | STAR
    for x, y in SKY:
        f[y, x] = True
    # Rays start on the first pixel clear of the disc (centre 23.5,15.5; r 4.6).
    r = max(0, round(FLASH_PEAK * (1 - angle / FLASH_CONE)))
    for k in range(r):
        f[15, 29 + k] = f[15, 18 - k] = f[21 + k, 23] = f[10 - k, 23] = True
    for j in range(3, 3 + round(0.6 * r)):  # diagonals shorter: a star, not a wheel
        f[16 + j, 24 + j] = f[15 - j, 23 - j] = f[15 - j, 24 + j] = f[16 + j, 23 - j] = True
    return f


def pack(f):
    # Row-major, 6 bytes per row, MSB = leftmost pixel — the vmu.rs framebuffer layout.
    return np.packbits(f, axis=1).flatten()


def rust(frames):
    out = [
        "// SPDX-License-Identifier: GPL-3.0-or-later",
        "",
        "// GENERATED by tools/vmu-pulsar/bake_frames.py — do not edit by hand.",
        "// Regenerate from tools/vmu-pulsar/README.md.",
        "",
        "use super::LCD_BYTES;",
        "",
        "/// The rotating-pulsar frames, raw content (no battery overlay, not rotated).",
        "#[rustfmt::skip]",
        f"pub const PULSAR_FRAMES: [[u8; LCD_BYTES]; {len(frames)}] = [",
    ]
    for i, f in enumerate(frames):
        out.append(f"    // frame {i}")
        out.append("    [")
        packed = pack(f)
        for y in range(H):
            row = ", ".join(f"0x{b:02X}" for b in packed[y * 6:(y + 1) * 6])
            art = "".join("#" if p else "." for p in f[y])
            out.append(f"        {row}, // {art}")
        out.append("    ],")
    out.append("];")
    return "\n".join(out) + "\n"


def preview(frames, path, scale=6, ms=300):
    bg, px = (168, 186, 164), (28, 40, 36)  # VMU LCD: dark pixels on grey-green
    ims = []
    for f in frames:
        rgb = np.where(f[..., None], np.array(px, np.uint8), np.array(bg, np.uint8))
        ims.append(Image.fromarray(rgb).resize((W * scale, H * scale), Image.NEAREST))
    ims[0].save(path, save_all=True, append_images=ims[1:], duration=ms, loop=0)


def main():
    src, dst = Path(sys.argv[1]), Path(sys.argv[2])
    angles = json.loads((src / "angles.json").read_text())
    frames = [compose(load(src / f"f{i:02d}.png"), a) for i, a in enumerate(angles)]
    dst.write_text(rust(frames))
    if len(sys.argv) > 3:
        preview(frames, sys.argv[3])


if __name__ == "__main__":
    main()
